name: 'Build Wheels'
description: 'Build wheels for ofrak'
inputs:
  python-version:
    description: 'Python version to build for'
    required: true
  os:
    description: 'Operating system'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: false

    - name: Setup LFS cache
      uses: ./.github/actions/lfs-cache

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: |
          requirements-*.txt

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build frontend
      shell: bash -euxo pipefail {0}
      run: make -C ofrak_core src/ofrak/gui/public

    - name: Install build tools
      shell: bash -euxo pipefail {0}
      run: |
        make requirements-build

    - name: Build ofrak wheels with cibuildwheel
      shell: bash -euxo pipefail {0}
      env:
        CIBW_SKIP: "*-win32 *-manylinux_i686"
        CIBW_ARCHS_WINDOWS: "AMD64"
        CIBW_ARCHS_MACOS: "x86_64 arm64"
        CIBW_ARCHS_LINUX: "x86_64"
        CIBW_BUILD_VERBOSITY: 1
      run: |
        # Convert Python version to cibuildwheel format (3.9 -> 39)
        PY_VERSION_NO_DOT="${{ inputs.python-version }}"
        PY_VERSION_NO_DOT=${PY_VERSION_NO_DOT//./}
        export CIBW_BUILD="cp${PY_VERSION_NO_DOT}-*"
        cd ofrak_core
        cibuildwheel --output-dir ../wheelhouse
        ls -la ../wheelhouse

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: ofrak-wheels-${{ inputs.os }}-py${{ inputs.python-version }}
        path: wheelhouse/
        retention-days: 30
