name: 'Build Source Distribution'
description: 'Build a source distribution for an OFRAK package'
inputs:
  package-name:
    description: 'Name of the package to build'
    required: true
  source-dir:
    description: 'Source directory containing the package'
    required: true
  lfs:
    description: 'Whether this package requires LFS'
    required: false
    default: 'false'
  python-version:
    description: 'Python version to use for building'
    required: false
    default: '3.9'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: false

    - name: Setup LFS cache
      if: ${{ inputs.lfs == 'true' }}
      uses: ./.github/actions/lfs-cache

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install build tools
      shell: bash
      run: |
        python -m pip install -r pip-requirements.txt
        pip install build

    - name: Build source distribution
      shell: bash
      run: |
        cd ${{ inputs.source-dir }}
        python -m build --sdist --outdir ${{ github.workspace }}/dist

    - name: List built packages
      shell: bash
      run: |
        echo "Built ${{ inputs.package-name }} packages:"
        ls -la dist/

    - name: Upload source distribution
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.package-name }}-sdist
        path: dist/
        retention-days: 30