#!/bin/bash
set -e

# Check required commands
command -v docker >/dev/null 2>&1 || { echo "Error: Docker is required"; exit 1; }
command -v git >/dev/null 2>&1 || { echo "Error: Git is required"; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "Error: Python 3 is required"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVCONTAINER_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(dirname "$DEVCONTAINER_DIR")"
CONFIG_FILE="$DEVCONTAINER_DIR/config.local.txt"
DEFAULT_CONFIG="ofrak-ghidra.yml"

cd "$REPO_ROOT"

# Create config file if missing
if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "$DEFAULT_CONFIG" > "$CONFIG_FILE"
    echo "============================================================"
    echo "Created $CONFIG_FILE with default: $DEFAULT_CONFIG"
    echo "Edit this file to use a different configuration."
    echo "============================================================"
fi

# Create docker-compose.local.yml if missing (required by devcontainer.json)
LOCAL_COMPOSE="$DEVCONTAINER_DIR/docker-compose.local.yml"
if [[ ! -f "$LOCAL_COMPOSE" ]]; then
    cat > "$LOCAL_COMPOSE" << 'EOF'
# Local customizations - see README.md for examples
services: {}
EOF
fi

OFRAK_CONFIG=$(cat "$CONFIG_FILE" | tr -d '[:space:]')

# Validate config exists
if [[ ! -f "$OFRAK_CONFIG" ]]; then
    echo "ERROR: Config file not found: $OFRAK_CONFIG"
    echo "Available configs:"
    ls -1 ofrak-*.yml 2>/dev/null || echo "  (none found)"
    exit 1
fi

# Check for Binary Ninja requirement
if grep -q "ofrak_binary_ninja" "$OFRAK_CONFIG" 2>/dev/null; then
    MISSING=()
    [[ ! -f "serial.txt" ]] && MISSING+=("serial.txt")
    [[ ! -f "license.dat" ]] && MISSING+=("license.dat")

    if [[ ${#MISSING[@]} -gt 0 ]]; then
        echo "============================================================"
        echo "ERROR: Binary Ninja license files missing!"
        echo "============================================================"
        echo "Config '$OFRAK_CONFIG' requires Binary Ninja."
        echo "Missing files: ${MISSING[*]}"
        echo ""
        echo "Either:"
        echo "  1. Add serial.txt and license.dat to repo root, OR"
        echo "  2. Edit $CONFIG_FILE to use a different config:"
        echo "     - ofrak-ghidra.yml (recommended)"
        echo "     - ofrak-angr.yml"
        echo ""
        echo "See .devcontainer/README.md for details."
        echo "============================================================"
        exit 1
    fi
fi

# Check build dependencies (on host - requires Python + PyYAML)
if ! python3 -c "import yaml" 2>/dev/null; then
    echo "ERROR: PyYAML is required on the host to build OFRAK images."
    echo "Install with: pip3 install -r requirements-build-docker.txt"
    exit 1
fi

# Process config: generates .devcontainer-config.yml, .packages, .env
# Returns base image name on stdout
BASE_IMAGE_NAME=$(python3 "$SCRIPT_DIR/process_config.py" "$OFRAK_CONFIG" "$DEVCONTAINER_DIR" "$REPO_ROOT" "$(whoami)")
DEVCONTAINER_CONFIG="$DEVCONTAINER_DIR/.devcontainer-config.yml"

echo "Building OFRAK base image..."
echo "  Config: $OFRAK_CONFIG (devcontainer variant without frontend)"
echo "  Image:  $BASE_IMAGE_NAME"

# Build base image (build_image.py handles Binary Ninja secrets via extra_build_args in yml)
python3 build_image.py --config "$DEVCONTAINER_CONFIG" --base --target develop

# Generate Dockerfile from Dockerfile.base + Dockerfile.local (proper multi-stage)
DOCKERFILE_BASE="$DEVCONTAINER_DIR/Dockerfile.base"
DOCKERFILE_LOCAL="$DEVCONTAINER_DIR/Dockerfile.local"
DOCKERFILE_GENERATED="$DEVCONTAINER_DIR/Dockerfile"

# Create empty Dockerfile.local if it doesn't exist
if [[ ! -f "$DOCKERFILE_LOCAL" ]]; then
    cat > "$DOCKERFILE_LOCAL" << 'EOF'
# Local Dockerfile customizations - this file is gitignored
# Add RUN commands or new stages here to extend Dockerfile.base
EOF
fi

# Header comment for generated file
HEADER="# AUTO-GENERATED - DO NOT EDIT
# This file is generated by initialize.sh from Dockerfile.base + Dockerfile.local
# To customize, edit Dockerfile.local
"

echo "Generating Dockerfile from base + local..."
{
    echo "$HEADER"
    echo "# === Dockerfile.base ==="
    cat "$DOCKERFILE_BASE"
    echo ""
    echo "# === Dockerfile.local ==="
    cat "$DOCKERFILE_LOCAL"
} > "$DOCKERFILE_GENERATED"

echo "Base image built successfully."
