#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVCONTAINER_DIR="$(dirname "$SCRIPT_DIR")"
PACKAGES_FILE="$DEVCONTAINER_DIR/.packages"

echo "Installing OFRAK packages in development mode..."

# Install packages from config (generated by initialize.sh)
if [[ -f "$PACKAGES_FILE" ]]; then
    echo "Installing packages from config..."
    while IFS= read -r pkg; do
        [[ -z "$pkg" ]] && continue
        if [[ -d "$pkg" ]]; then
            echo "  Installing: $pkg"
            make -C "$pkg" develop
        else
            echo "  WARNING: Package directory not found: $pkg"
        fi
    done < "$PACKAGES_FILE"
else
    echo "WARNING: No packages file found, falling back to make develop"
    make develop
fi

echo "Building frontend from source..."
make -C ofrak_core src/ofrak/gui/public

echo "Installing pre-commit hooks..."
pre-commit install --install-hooks

# Check license status
LICENSE_FILE="ofrak_core/src/ofrak/license/license.json"
if [[ ! -f "$LICENSE_FILE" ]]; then
    echo ""
    echo "============================================================"
    echo "IMPORTANT: OFRAK License Required"
    echo "============================================================"
    echo ""
    echo "OFRAK requires license acceptance before use."
    echo ""
    echo "Community License (personal/educational use):"
    echo "    ofrak license --community"
    echo ""
    echo "    This will display the full license text for you to review"
    echo "    and agree to interactively. The license defines exactly"
    echo "    what constitutes personal and educational use."
    echo ""
    echo "    Or, to accept non-interactively:"
    echo "    ofrak license --community --i-agree"
    echo ""
    echo "Pro License (commercial use):"
    echo "    ofrak license"
    echo ""
    echo "Full license: https://ofrak.com/docs/license.html"
    echo "============================================================"
fi

echo ""
echo "Setup complete!"
