#!/usr/bin/env python3
"""
Process OFRAK config for devcontainer setup.

Reads the source config yml, generates devcontainer-specific config,
extracts settings, and writes .env and .packages files.
"""

import argparse
import hashlib
import re
import subprocess
import sys
from pathlib import Path

import yaml


def get_git_revision() -> str:
    """Get short git revision hash."""
    result = subprocess.run(
        ["git", "rev-parse", "--short=8", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def generate_project_name(repo_root: str) -> str:
    """Generate unique docker-compose project name from workspace path."""
    raw_name = "ofrak" + repo_root.lower().replace("/", "_")
    # Truncate if exceeding 63 char limit (Docker label constraint)
    if len(raw_name) > 63:
        hash_suffix = hashlib.sha256(repo_root.encode()).hexdigest()[:8]
        return f"{raw_name[:54]}_{hash_suffix}"
    return raw_name


def process_config(
    source_config: Path, devcontainer_dir: Path, repo_root: str, username: str
) -> str:
    """
    Process source config and generate devcontainer-specific files.

    Returns base image name.
    """
    with open(source_config) as f:
        config = yaml.safe_load(f)

    # Remove frontend from packages (built separately in devcontainer)
    packages = [p for p in config.get("packages_paths", []) if p != "frontend"]
    config["packages_paths"] = packages

    # Prefix base_image_name with devcontainer-
    config["base_image_name"] = "devcontainer-" + config["base_image_name"]

    # Write devcontainer-specific config
    devcontainer_config = devcontainer_dir / ".devcontainer-config.yml"
    with open(devcontainer_config, "w") as f:
        yaml.dump(config, f, default_flow_style=False)

    # Extract base image name with revision tag
    rev = config.get("image_revision") or get_git_revision()
    base_image = f"{config['registry']}/{config['base_image_name']}:{rev}"

    # Extract backend from entrypoint (if present)
    entrypoint = config.get("entrypoint", "")
    match = re.search(r"--backend\s+(\S+)", entrypoint)
    default_backend = match.group(1) if match else ""

    # Check if Ghidra server should auto-start
    start_ghidra = "true" if "ofrak_ghidra.server start" in entrypoint else ""

    # Write packages file (add pytest_ofrak for dev testing)
    if "ofrak_core" in packages and "pytest_ofrak" not in packages:
        packages = packages + ["pytest_ofrak"]

    packages_file = devcontainer_dir / ".packages"
    with open(packages_file, "w") as f:
        for pkg in packages:
            f.write(f"{pkg}\n")

    # Write .env file
    env_file = devcontainer_dir / ".env"
    with open(env_file, "w") as f:
        f.write("# Generated by process_config.py - do not edit manually\n")
        f.write("# To change config, edit config.local.txt and rebuild container\n")
        f.write(f"OFRAK_BASE_IMAGE={base_image}\n")
        f.write(f"OFRAK_DEFAULT_BACKEND={default_backend}\n")
        f.write(f"COMPOSE_PROJECT_NAME={generate_project_name(repo_root)}\n")
        f.write(f"OFRAK_START_GHIDRA_SERVER={start_ghidra}\n")
        f.write(f"USERNAME={username}\n")
        f.write(f"WORKSPACE_FOLDER={repo_root}\n")

    return base_image


def main():
    parser = argparse.ArgumentParser(description="Process OFRAK config for devcontainer")
    parser.add_argument("source_config", type=Path, help="Source config yml file")
    parser.add_argument("devcontainer_dir", type=Path, help="Devcontainer directory")
    parser.add_argument("repo_root", help="Repository root path")
    parser.add_argument("username", help="Username for container")
    args = parser.parse_args()

    if not args.source_config.exists():
        print(f"ERROR: Config file not found: {args.source_config}", file=sys.stderr)
        sys.exit(1)

    base_image = process_config(
        args.source_config, args.devcontainer_dir, args.repo_root, args.username
    )

    # Print base image for use by caller
    print(base_image)


if __name__ == "__main__":
    main()
