ghidra_install:
  log_file: ~/.ghidra/.ghidra_11.3.2_PUBLIC/application.log
  path: /opt/rbs/ghidra_11.3.2_PUBLIC
  version: 11.3.2
server:
  analysis:
    host: localhost
    port: 13300
  pass: changeme
  repository:
    host: localhost
    port: 13100
  user: root
