name: Build OFRAK Wheels

# Trigger on push to feature/windows_tests branch
on:
  push:
    branches:
      - feature/windows_tests
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build OFRAK wheels on ${{ matrix.os }} for Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11']
        
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Build OFRAK (ofrak_core) wheel
        run: |
          cd ofrak_core
          python -m build --wheel --outdir ../wheelhouse
        shell: bash

      - name: List built wheels
        run: |
          echo "Built wheels:"
          ls -la wheelhouse/ || echo "No wheelhouse found"
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: ofrak-${{ matrix.os }}-py${{ matrix.python-version }}
          path: wheelhouse/
          retention-days: 30

  build_sdist:
    name: Build source distributions
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build OFRAK source distribution
        run: |
          mkdir -p sdist
          cd ofrak_core
          python -m build --sdist --outdir ../sdist
          cd ..

      - name: List built sdists
        run: |
          echo "Built source distributions:"
          ls -la sdist/

      - name: Upload source distributions
        uses: actions/upload-artifact@v4
        with:
          name: source-distributions
          path: sdist/
          retention-days: 30
